flight_dbt:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: postgres
      pass: postgres
      dbname: flights
      schema: public
  target: dev
